# Generated by Django 2.2 on 2020-06-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='shifting',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
